///////////////////////////////////////////////////////////////////////////////
//
//                          IMPORTANT NOTICE
//
// The following open source license statement does not apply to any
// entity in the Exception List published by FMSoft.
//
// For more information, please visit:
//
// https://www.fmsoft.cn/exception-list
//
//////////////////////////////////////////////////////////////////////////////
/*
 *   This file is part of mGEff, a component for MiniGUI.
 *
 *   Copyright (C) 2008~2018, Beijing FMSoft Technologies Co., Ltd.
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 *   Or,
 *
 *   As this program is a library, any link to this program must follow
 *   GNU General Public License version 3 (GPLv3). If you cannot accept
 *   GPLv3, you need to be licensed from FMSoft.
 *
 *   If you have got a commercial license of this program, please use it
 *   under the terms and conditions of the commercial license.
 *
 *   For more information about the commercial license, please refer to
 *   <http://www.minigui.com/blog/minigui-licensing-policy/>.
 */
#include <stdlib.h>

const char *g_lines[] = {
" ]g                                     <w",
" ]Q;                                    jQ",
" ]Q[                                    dQ",
" ]QL                                   .QQ",
" ]QQ,                                  jQQ",
" ]QQQwa_a_a_a_a_a_a_a_a_a_a_a_a_a_a_aawQWQ",
" ]QQQWWQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQWWQQQ",
" ]QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ",
" ]QQQP!^~~~~~~~~~~~~~~~~~~~~~~~~~~~<wQQQQQ",
" ]QQ(                            _yQQQQQQQ",
" ]QP                          .amQQQQQQQQQ",
" ]Q[                        _wWWQQQQQQQQQQ",
" ]Q`                      _yQQWQQQQQQQQQQQ",
" ]Q                    .amQQQQQQQQQQQQQQQQ",
" -^                  _wQWQQQQQQQQQQQQQQQQQ",
"                   <yQQWQQQQQQQQQQQQQQQQQP",
"                .amQQQQQQQQQQQQQQQQQQQWq`",
"              _wQQQQQQQQQQQQQQQQQQQQD`",
"            syQQQQQQQQQQQQQQQQQQQQP^",
"         .aQWQQQQQQQQQQQQQQQQQQ@q`",
"       _wQQQQQQQQQQQQQQQQQQQQD`",
"     syQQQQQQQQQQQQQQQQQQQQP`",
"  _aQQQQQQQQQQQQQQQQQQQQ@!`",
" ]QQQQQQQQQQQQQQQQQQQQD`",
" ]QQQQQQQQQQQQQQQQQWY`",
"  `9QQQQQQQQQQQQQ@!",
"    -9WWQQQQQQQP`",
"       qVQQQQW(",
"         `4QWQQg,",
"           -q$QQQma.",
"              `9QQQQw,",
"                -qQWWQg,",
"                   `$QQQQa.",
"                     -9QWWQw,",
" __.                    q$QWQgc",
" ]Q.                      `9QQWQa.",
" ]Q;                        -qQWWQw,",
" ]Q[                           `VQQQmc",
" ]Qm                             -9WQWQa,",
" ]QQw,                              q$WQQw",
" ]QQQQQWWWWWWWWWQQWWWQWWWWWWWWQQQWWQWWWQQQ",
" ]QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ",
" ]QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ",
" ]QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ",
" ]QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ",
" ]QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQWQQQWQQQQ",
" ]QQQQQQQQQQQQQQQQQQQQQQQQQWQQQQQQQQQQQQQQ",
" ]QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ",
" ]QQQQQQQQQQQQQQQQQQQQQQQWQQQQQQQWQQQQQQQQ",
" ]QQQTq`````````````````````````````qq$QQQ",
" ]QQ`                                  4QQ",
" ]QF                                   -WQ",
" ]Q[                                    $Q",
" ]Q`                                    jQ",
" )T                                     )T",
"",
"----",
"",
" _a                        _w",
" ]Q>                       mQ",
" ]Qk                      _QQ",
" ]QQgasssassasssssssssssaaQQQ      _wmmg/",
" ]QQQWWWWWWWWBWWWWWWWWWWWWQQQ     _QWQQQQL",
" ]QQQQQQWQWQWQQQQQWQQWQQWQQQQ    .QQQQQQQQc",
" ]QQQQQQQQQQQQQQQQQQQQQQQQQQQ    )QQQQQQQQm",
" ]QQQQQQQQQQQQQQQQQQQQQQQQQQQ    ]QQQQQQQQQ",
" ]QQQQQQQQQQQQQQQQQQQQQQQQQQQ    ]QQQQQQQQW",
" ]QQQQQQQQQQQQQQQQQQQQQQQQQQQ    -QQQQQWQQf",
" ]QQQQQQQQQQQQQQQQQWQQQQQQQQQ     4WQQQQQ@`",
" ]QQQQQWWWWWWWWWWWWWWWWWWWWWW      qQQQQD`",
" ]QW`                               -``~",
" ]Q[",
" ]W",
"",
"----",
"",
" _a                        _a",
" ]Q;                       jQ",
" ]QL                      .QQ",
" ]QQw,___________________ayQQ",
" ]QQQQQQQQQQQQQQQQQQQQQQQQQQQ",
" ]QQQQQQQQQQQQQQQQQQQQQQQQQQQ",
" ]QQQQQQQQQQQQQQQQQQQQQQQQQQQ",
" ]QQQQQQQQQQQQQQQQQQQQQQQQQQQ",
" ]QQQQQQQQQQQQQQQQQQQQQQQQQQQ",
" ]QQQQQQQQQQQQQQQQQQQQQQQQQQQ",
" ]QQQQQQQQQQQQQQQQQQQQQQQQQQQ",
" ]QQQQQQQQQQQQQQQQQQQQQQQQQQQ",
" ]QW!-----------------`Qm,  .",
" ]Q[                   -QQ,",
" ]Q`                    ]WQ,",
"  .                      $Qm.",
"                         jQQL",
" _a                      ]QQQ",
" ]Q;                     dQQQ;",
" ]Q6                   .jQQQQ[",
" ]QQQwwawawawawawawawwwQQQQQQf",
" ]QQQWWQWQWQWQWQWQWQWWQQQQQQQ[",
" ]QQQQQQQQQQQQQQQQQQQQQQQQQQQ(",
" ]QQQQQQQQQQQQQQQQQQQQQQQQQQQ`",
" ]QQQQQQQQQQQQQQQQQQQQQQQQQQF",
" ]QQQQQQQQQQQQQQQQQQQQQQQQQW`",
" ]QQQQQQQQQQQQQQQQQQQQQQQQW`",
" ]QQQQQQQQQQQQQQQQQQQQQQQP`",
" ]QQWVTTVTTTTTTTTTTTTTT!`",
" ]QP",
" ]Q`",
" )T",
"",
"----",
"  .                         .",
" ]Q,                       jQ",
" ]Q[                       QQ",
" ]QQ,                    .jQQ       .ss,",
" ]QQQQmmmmmmmmmmmmmmmmmmQWQQQ      jQQWQm,",
" ]QQQQQQQQQQQQQQQQQQQQQQQQQQQ     jQQQQQQQ,",
" ]QQQQQQQQQQQQQQQQQQQQQQQQQQQ    _QQQQQQQQL",
" ]QQQQQQQQQQQQQQQQQQQQQQQQQQQ    ]QQQQQQQQW",
" ]QQQQQQQQQQQQQQQQQQQQQQQQQQQ    ]QQQQQQQQQ",
" ]QQQQQQQQQQQQQQQQQQQQQQQQQQQ    )QQQQQQQQE",
" ]QQQQQQQQQQQQQQQQQQQQQQQQQQQ     $QQQQQQQ[",
" ]QQQQQQQQQQQQQQQQQQQQQQQQQQQ     -QQQQQQf",
" ]QQDqqqqqqqqqqqqqqqqqqqqqqqq      -qH8T^",
" ]QP",
" ]Q`",
" `!",
"",
"----",
"",
"",
"                 .__as_,,",
"             _awQQQQQWQQQQmw,",
"           _yQWWQQQQQQQQQQQQQQw,",
"         _yQQQQQQQQQQQQQQQQQQQWQa.",
"        sWQQQQQQQQQQQQQQQQQQQQQQQm,",
"       jWQQQQQQQQQQQQQQQQQQQQQQQQQQa",
"      jQQQQQQQQQQQQQQQQQQQQQQQQQQQQQL",
"     jQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQL",
"    <QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQL",
"   _QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ/",
"   jQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQm.",
"  _QQQQQQQQQQWVTq!``^~^^``qq9HWQQQQQQQQQL",
"  jQQQQQQQD!~                  `q$QQQQQQQ.",
" .QQQQQQP`                        `9QQQQQ[",
" ]QQQQ@`                            `$QQQm",
" jQQQP                               -$WQQ;",
".QQQP                                 -$QQ[",
".QQW`                                  +QQL",
"<QQ[                                    4Qh",
"]WQ`                                    ]QW",
"]WE                                     :QQ",
"]Qf                                      QQ",
"]Qf                                      QQ",
"]Qf              m[                     .QW",
"]Qf             .Qf                     <QE",
")Qk             =Qf                     jWf",
"=Qm             ]Qf                     QW(",
"-QQc            jQf                    jWW",
" QQQc          jQQf                   _mQF",
" $QQWQmmmmgmmmQQWQf                   yQQ(",
" jQQQQQQWQQQWQQQQQf                  jQQ@",
" ]QQQQQQQQQQQQQQQQf                 jQQQf",
" -QQQQQQQQQQQQQQQQf               .wQQQQ`",
"  WWQQQQQQQQQQQQQQf              _mQQQQQ",
"  ]QQQQQQQWQQQQQQQf            .wQQQQQQQ/",
"  =QQQQQQQQQQQQQQQf          .wQQQQQQQQQQc",
"   $QQQQQQQQQQQQQQf         <QQWQQQQQQQQQQk",
"   )WQQQQQQQQQQQWQf         )VVHVVHVHVHVVHC",
"    qqqqqqqqqTVQQQf",
"               `QQf",
"                4Qf",
"                ]Wf",
"                :Qf",
"                 T(",
"",
"----",
"",
"                                        ]g",
"                                        jQ",
"                                        mQ",
"                                       <QQ",
"                                     .<mQQ",
"         _awygmmmmmmmmmmmmmmmmmmmmmmQQQQQQ",
"       amQQQWQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ",
"     _yQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ",
"    _mQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ",
"   .mQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ",
"   jQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ",
"  =QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ",
"  dQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ",
" _QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ",
" jQQQQQQQQQBVTTTTYTTYTTYTTTTTTTTTTTT9$QQQQ",
" mQQQQQWY^                            -$QQ",
".QQQQQF                                -QQ",
"=QQQQ[                                  $Q",
"]WQQF                                   3Q",
"]WQQ`                                   jQ",
"]QQ@                                    `q",
"]QQf",
"]QQf",
"]QQf",
")WQf",
"-WQL",
" WQm",
" jQQ.",
" )WQc                                   ]m",
"  $WQ.                                  jQ",
"  )WW6                                  mQ",
"   4WQg.                               _QQ",
"    4QQQc.                             dQQ",
"     4WQWQwa,_.                     _syQQQ",
"      `$QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQWQQQ",
"        `9$QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ",
"           -`qqTTTqTTqTTqTTqTTqTqTTq9HQQQQ",
"                                      -$QQ",
"                                       )WQ",
"                                        $Q",
"                                        jQ",
"                                        -`",
"----",
" __.                                    __",
" ]Q.                                    jQ",
" ]Q;                                    jQ",
" ]Q[                                    QQ",
" ]Qh                                   <WQ",
" ]QQa                                 _mQQ",
" ]QQQQgwwwwwywwwwwwwwwwwwwwwwwwwwwwwymQQQQ",
" ]QQQQQWQQQQQQQQQWQQQQQQQQQWQQQQQQQQQWQQQQ",
" ]QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ",
" ]QQQQQQQQQQQQQQQQQQQQQQWQQQQQQQQQQQQQQQQQ",
" ]QQQQQQQQQQQQQQQQQQQQWQQQQQQQQQQQQQQQQQQQ",
" ]QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQWQQQQQQQQQ",
" ]QQQQQQQQQQQQQQQQQWQQQQQQQQQQQQQQQQQQWQQQ",
" ]QQQQQQQQQQQQQQQQQQQQQQQQQQQQQWQQQQQQQQQQ",
" ]QQQQQQQQQQQQQQWQQQQQQQQQQQQQQQQQQQQQQQQQ",
" ]QQQQQQQQQQQQQQQQQQQQQQQWQQQQQQQQQQQQQQQQ",
" ]QQP^                               -qWQQ",
" ]Q@                                   )WQ",
" ]Q[                                    WQ",
" ]Q`                                    3Q",
" ]Q`                                    jQ",
" ]T                                     ]T",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"----",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"       _aaas.",
"     .wQWWWWQa",
"    _QQQQQQQQQ6",
"   .mQQQQQQQQQQL                      ,",
"   jQQQQQQQQQQQQ                     :QQwc.",
"  <QQQQQQQQQQQQQ;                    =QQWWQma,",
"  jQQQQQQQQQQQQQ[                    )QQQQQQQQQwa.",
" _QQQQQQQQQQQQQQf                    ]WQQQQQQQQQWQmw,.",
" ]QQQQQQQQQQQQQQ[                    ]QQQQQQQQQQQQQWQQga,",
" dQQQQQQQQQQQQQQ`                    jQQQQQQQQQQQQQQQQQWQmw,,",
" QQQQQQQQQQQQQQ@                     jQQQQQQQQQQQQQQQQQQQQQQQga,",
".QQQQQQQQQQQQQQf                     mQQQQQQQQQQQQQQQQQQQQQQQQQQQwc.",
"<QQQQQQQQQQQQQQ`                     QWQQQQQQQQQQQQQW-`9WWQQQQQQQWWQma,",
"]WQQQQQQQQQQQQP                      QQQQQQQQQQQQQQQ#    -q9QQQQQQQQQQQQwa.",
"]WQQQQQQQQQQQQ`                     :QQQQQQQQQQQQQQQD        `QQQQQQQQQQQWQm",
"]QQQQQQQQQQQQF                      )QQQQQQQQQQQQQQQk         QQQQQQQQQQQQQQ",
"]QQQQQQQQQQQW`                      ]QQQQQQQQQQQQQQQk         QQQQQQQQQQQQQQ",
"]QQQQQQQQQQQf                       jQQQQQQQQQQQQQQQf         QQQQQQQQQQQQQQ",
"]QQQQQQQQQQD                        mQQQQQQQQQQQQQQQf         QQQQQQQQQQQQQQ",
"]WQQQQQQQQQ`                        QQQQQQQQQQQQQQQQ[         QQQQQQQQQQQQQQ",
")WQQQQQQQQF                        =QQQQQQQQQQQQQQQQ(         QQQQQQQQQQQQQQ",
":QQQQQQQQQ`                        ]QQQQQQQQQQQQQQQQ`         QQQQQQQQQQQQQQ",
"-QQQQQQQQf                         dQQQQQQQQQQQQQQQW          QQQQQQQQQQQQQQ",
" QQQQQQQQ`                         QQQQQQQQQQQQQQQQB          QQQQQQQQQQQQQQ",
" dQQQQQQE                         ]QQQQQQQQQQQQQQQQk          QQQQQQQQQQQQQQ",
" ]QQQQQQ[                         jQQQQQQQQQQQQQQQQf          QQQQQQQQQQQQQQ",
" ]QQQQQQ`                        .QQQQQQQQQQQQQQQWQ(          QQQQQQQQQQQQQQ",
"  QQQQQQ                         jQQQQQQQQQQQQQQQQQ`          QQQQQQQQQQQQQQ",
"  4QQQQQ                        .QWQQQQQQQQQQQQQQQD           QQQQQQQQQQQQQQ",
"  ]QQQQQ.                       jWWQQQQQQQQQQQQQQQf           QQQQQQQQQQQQQQ",
"   QQQQQ;                      _WWQQQQQQQQQQQQQQQQ`           QQQQQQQQQQQQQQ",
"   3QQQQ[                      jQQQQQQQQQQQQQQQQQD            QQQQQQQQQQQQQQ",
"   -QQQQm                     jWQQQQQQQQQQQQQQQQQ[            QQQQQQQQQQQQQQ",
"    4QQQQc                   _QWQQQQQQQQQQQQQQQQW`            QQQQQQQQQQQQQQ",
"    -QWQQQ.                 _QQQQQQQQQQQQQQQQQQQf             QQQQQQQQQQQQQQ",
"     ]QQQWg                _QQQQQQQQQQQQQQQQQQQW`             QQQQQQQQQQQQQQ",
"      4QQQQg.             jQQQQQQQQQQQQQQQQQQQW[              QQQQQQQQQQQQQQ",
"      -QQQQQm/          _mQWQQQQQQQQQQQQQQQQQQE               QQQQQQQQQQQQQQ",
"       +WQQQQQma,   ._amQQQQQQQQQQQQQQQQQQQQQW`               QQQQQQQQQQQQQQ",
"        )QQQQQQWQQQQQQQQQQQQQQQQQQQQQQQQQQQQW`                QQQQQQQQQQQQQQ",
"         )QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ(                 QQQQQQQQQQQQQQ",
"          )QWQQQQQQQQQQQQQQQQQQQQQQQQQQQQQW(                  QQQQQQQQQQQQQQ",
"           -WQQQQQQQQQQQQQQQQQQQQQQQQQQQQW^                   QQQQQQQQQQQQQQ",
"            -4WQQQQQQQQQQQQQQQQQQQQQQQQQD`                    QQQQQQQQQQQQQQ",
"              `$QQQQQQQQQQQQQQQQQQQQQQW!                      QQQQQQQQQQQQQQ",
"                `9QQQQQQQQQQQQQQQQQQ@!                        -q$QQQQQQQQQQQ",
"                  -q9QWQQQQQQQQQQ@T`                             -q$QQQQQQQQ",
"                      -`qqqTqq!``                                   -q$QQQQQ",
"                                                                       -q$QQ",
"                                                                          ~q",
"",
"",
"",
"----",
"",
"",
"   _aaa.",
"  jWWWWQc",
" jWQQQQQQc",
".QQQQQQQQQ.",
"]QQQQQQQQQ[",
"]QQQQQQQQQ[",
"]WQQQQQQQQ[",
"-QQQQQQQQW`",
" ]QQQQQQQ[",
"  4WQQQW!",
"   -qqq`",
"",
"",
"----",
"",
"                __aaaaaaas,,",
"           .<wmQQQQWWWWWWWQQQwa,",
"         _yQQWWQQQQQQQQQQQQQQQWQga",
"       _mQQQQQQQQQQQQQQQQQQQQQQQQWQc",
"     .yQQQQQQQQQQQQQQQQQQQQQQQQQQQWQm,",
"    _QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQa",
"   <QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQL",
"  _QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQL",
"  mQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ/",
" jQQQQQQQQQQWWWWWWWWWWWWWWWWWWWWQQQQQQQQQm",
" mWQWVq`~-                        -``T$WQQc",
":QQY                                   `$Qk",
"]Q[                                      $m",
"]Q                                       ]Q",
"]Q                                       jQ",
"]Qc                                     .QB",
":QQa.                                  _mQF",
" WQQQwa,,_                       .__awmQQQ[",
" ]QQQQWQQQQQQmmmmmmmmmmmmmmmmmQWQQQQQWQQQ@",
"  $QQQQQQQQQQQQQQQQQQQQQQQQQQQQWQQQQQQQQQ(",
"  +QWQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQF",
"   `QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQP",
"    -QWQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQf",
"     -4QQQQQQQQQQQQQQQQQQQQQQQQQQQQQ@`",
"       `$WQQQQQQQQQQQQQQQQQQQQQQQQW!",
"         `9QQQQQQQQQQQQQQQQQQQQQD!",
"            `9HWQQQQQQQQQQQQWTq`",
"                ~`qqqqqqq```",
"----",
NULL
};

